---
title: "Direct-Mail Fundraising Analysis"
author: "Bryan Clark"
date: "2020-08-15"
output: 
  html_document:
    highlight: default
    theme: cosmo
    toc: true
    toc_float: true
    df_print: tibble
---

```{r setup}
# customize output options 
knitr::opts_chunk$set(echo = TRUE, warning = FALSE, message = FALSE,
                      fig.width = 6, fig.asp = 0.618, out.width = "70%", 
                      fig.align = "center")

# rmarkdown
library(knitr)
library(kableExtra)

# set theme for plots
theme_set(theme_minimal(base_family = "Avenir"))

# The color-blind palette with grey:
cb_palette <- c("#999999", "#E69F00", "#56B4E9", "#009E73",
                "#F0E442", "#0072B2", "#D55E00", "#CC79A7")
```

# TL;DR

Use report in app like here: https://shiny.rstudio.com/gallery/soil-profiles.html

# 1. Case Overview

## 1.1 Goal

## 1.2 Follow-Up Questions

## 1.3 Assumptions

## 1.4 Success KPI

# 2. Data

## 2.1 Raw Data

```{r data}
library(tidyverse)

config <- config::get()
data_path <- fs::path(
  here::here(),
  config$data_dir, config$data_file
)

fundraising_raw_tbl <- read_csv(data_path) %>%
  janitor::clean_names()
```

## 2.2 Data Understanding

```{r}
fundraising_raw_tbl %>% glimpse()
```

```{r}
skimr::skim(fundraising_raw_tbl)
```

## 2.3 Data Exploration

boxplots/column plots of donation vs. no donation
correlation funnel explore

## 2.4 Data Preparation




# 3. Modeling

## 3.1 Data Partition

## 3.2 Base Model

## 3.3. XGBoost

```{r}
# this function will be used for most modeling
train_xgboost <- function(params_list, data_recipe, nfolds = 5, mode = c("regression", "classification")) {
  
  # tune xgboost model with given params (null for non entries)
  # return model and performance specs for mode
  
}

# this function will be used a lot
mlflow_training_experiment <- function(model_function, hyper_param_grid, ...) {
  # create an experiment and train across parameter grid
  # log results
}
```


# 4. Evaluation

## 4.1 Base Model

## 4.2 XGBoost

# 5. Deployment